server:
  port: 18002
spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/custom?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  #配置mybaits自定义类型转换类所在的包
  #type-handlers-package: com.medical.chain.config.typeHandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  http:
    proxy:
      enable: ${HTTP_PROXY:false}
      ip: ${HTTP_PROXY_IP:127.0.0.1}
      port: ${HTTP_PROXY_PORT:8001}
#柯博的医链创建凭证接口地址
saas:
  chain:
    createClaim:
    check:
