server:
  port: 18002
spring:
  datasource:
    url: jdbc:mysql://192.168.1.44:3306/custom?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
custom:
  http:
    proxy:
      enable: ${HTTP_PROXY:false}
      ip: ${HTTP_PROXY_IP:127.0.0.1}
      port: ${HTTP_PROXY_PORT:8001}
#柯博的医链创建凭证接口地址
saas:
  chain:
    createClaim: http://192.168.1.106:8080/interface/createClaim
    check: http://192.168.1.106:8080/api/v1/taas/check

